A3C_Config:

  # Gym Environment parameters
  env_type: 'gym'
  env_name: 'CartPole-v0'
  env_processes: 16
  seed_offset: 0
  render_env: False
  max_episode_length: 10000
  normalize_state: False

  # PyTorch Parameters
  torchSeed: 0

  # Policy Parameter
  memsize: 256

  # MLP Policy Parameter
  policy_hiddens : [128]

  # Optimizer Parameters
  learning_rate: 0.0001

  # Experiment Configs
  num_training_frames: 80000000
  moving_avg_coef: 0.99
  gamma: 0.99

  # A3C hyper-parameters
  num_steps: 10
  gae_lambda: 1.0
  value_loss_coef: 0.01
  grad_norm: 40

  # Logging Details
  exp_name: 'cartpole'
  log_dir: '/home/mayank/'